/*
 * Main_config.c
 *
 * Created: 6/1/2023 11:23:26 PM
 *  Author: Eng.Mostafa Ali
 */ 
#define GUEST_PASSWORD_ADDRESS	0x11
#define GUEST_PASSWORD_ADDRESS_CHECK	0x00
#define BLOCKED_MODE_ACTIVATE	0X1A

#define ADMIN_PASSWORD_ADDRESS			0X1C
#define ADMIN_PASSWORD_ADDRESS_CHECK	0x00

